[package]
name = "raman_core_rs"
version = "2.0.0"
edition = "2021"

[lib]
name = "raman_core_rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
ndarray = { version = "0.16", features = ["serde"] }
num-complex = { version = "0.4", features = ["serde"] }
numpy = "0.24"
pyo3 = { version = "0.24", features = ["abi3-py311", "extension-module"] }
rayon = "1.10"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
ndarray = { version = "0.16", features = ["serde"] }
num-complex = { version = "0.4", features = ["serde"] }