import React, { useCallback, useEffect, useMemo, useState } from 'react';
import {
  Atom, Beaker, Filter, Plus, X, Search, Sparkles, Loader2, ChevronRight,
  Package, ListFilter, AlertCircle,
} from 'lucide-react';

/**
 * AlchemistCanvas — combinatorial materials design.
 *
 * Three-pane workflow:
 *
 *   ┌──────────────────┬───────────────────┬───────────────────────┐
 *   │ Materials        │  Selected blocks  │  Ranked candidates    │
 *   │ library          │  + constraints    │  (mixture rules)      │
 *   │ (curated DB)     │  + generate       │  + pick → details     │
 *   └──────────────────┴───────────────────┴───────────────────────┘
 *
 * The combinator runs entirely on curated data (`/api/v2/alchemi/materials/
 * library` + `/api/v2/alchemi/materials/combinations`). The user can NOT
 * type in an arbitrary formula — every block in the system is a
 * literature-anchored material. The optional "Draft synthesis" button
 * passes a chosen candidate to /api/v2/alchemi/chat for a procedure;
 * the mixture properties are *not* generated by the LLM.
 */

const BACKEND_URL = (typeof window !== 'undefined' && window.raman) ? null : 'http://127.0.0.1:8000';

async function callBackend(path, opts = {}) {
  const api = (typeof window !== 'undefined' && window.raman) ? window.raman.api : null;
  if (api) return opts.method === 'POST' ? api.call(path, opts.body) : api.get(path);
  const res = await fetch(`${BACKEND_URL}${path}`, {
    method: opts.method || 'GET',
    headers: { 'Content-Type': 'application/json' },
    body: opts.body ? JSON.stringify(opts.body) : undefined,
  });
  if (!res.ok) {
    const text = await res.text();
    const err = new Error(`HTTP ${res.status}: ${text.slice(0, 200)}`);
    err.status = res.status;
    throw err;
  }
  return res.json();
}

function fmtNum(v, digits = 2) {
  if (v == null || Number.isNaN(v)) return '—';
  if (v === 0) return '0';
  const abs = Math.abs(v);
  if (abs >= 1e4 || abs < 0.01) return v.toExponential(digits);
  return Number(v).toFixed(digits);
}

const CATEGORY_COLORS = {
  Carbon:               '#0f766e',
  'Conducting polymer': '#7c3aed',
  'Metal oxide':        '#c2410c',
  Metal:                '#9a3412',
  Other:                '#475569',
};

export default function AlchemistCanvas() {
  const [library, setLibrary] = useState([]);
  const [libError, setLibError] = useState(null);
  const [selected, setSelected] = useState([]);            // array of block keys
  const [search, setSearch] = useState('');
  const [categoryFilter, setCategoryFilter] = useState(null);

  const [constraints, setConstraints] = useState({
    max_components: 3,
    step_pct: 25,
    min_capacitance_F_g: '',
    min_conductivity_S_m: '',
    min_voltage_window_V: '',
    max_cost_relative: '',
    require_all_selected: false,
  });

  const [generating, setGenerating] = useState(false);
  const [genError, setGenError] = useState(null);
  const [results, setResults] = useState(null);            // {total_evaluated, candidates}
  const [picked, setPicked] = useState(null);              // selected candidate
  const [draftBusy, setDraftBusy] = useState(false);
  const [draft, setDraft] = useState(null);                // {steps, rationale}
  const [draftError, setDraftError] = useState(null);

  // Load curated library on mount.
  useEffect(() => {
    (async () => {
      try {
        const d = await callBackend('/api/v2/alchemi/materials/library');
        setLibrary(d.library || []);
      } catch (e) {
        setLibError(e?.message || String(e));
      }
    })();
  }, []);

  // Persist selection across sessions (small affordance).
  useEffect(() => {
    try {
      const saved = localStorage.getItem('raman-alchemist-selected');
      if (saved) setSelected(JSON.parse(saved));
    } catch { /* ignore */ }
  }, []);
  useEffect(() => {
    try { localStorage.setItem('raman-alchemist-selected', JSON.stringify(selected)); } catch { /* ignore */ }
  }, [selected]);

  const filteredLibrary = useMemo(() => {
    const q = search.trim().toLowerCase();
    return library.filter(b => {
      if (categoryFilter && b.category !== categoryFilter) return false;
      if (!q) return true;
      return (b.display_name + ' ' + b.formula + ' ' + b.type + ' ' + b.category)
        .toLowerCase().includes(q);
    });
  }, [library, search, categoryFilter]);

  const categories = useMemo(() => {
    const set = new Map();
    for (const b of library) set.set(b.category, (set.get(b.category) || 0) + 1);
    return [...set.entries()].sort();
  }, [library]);

  const toggleBlock = (key) => {
    setSelected(s => s.includes(key) ? s.filter(k => k !== key) : [...s, key]);
  };

  const numericConstraints = () => {
    const out = {};
    const f = ['min_capacitance_F_g', 'min_conductivity_S_m', 'min_voltage_window_V', 'max_cost_relative'];
    for (const k of f) {
      const v = constraints[k];
      if (v === '' || v == null) continue;
      const n = Number(v);
      if (!Number.isNaN(n)) out[k] = n;
    }
    return out;
  };

  const generate = useCallback(async () => {
    if (selected.length === 0) {
      setGenError('Pick at least one block from the library.');
      return;
    }
    setGenerating(true);
    setGenError(null);
    setDraft(null);
    setPicked(null);
    try {
      const body = {
        selected,
        max_components: constraints.max_components,
        step_pct: constraints.step_pct,
        require_all_selected: constraints.require_all_selected,
        ...numericConstraints(),
        top_n: 30,
      };
      const d = await callBackend('/api/v2/alchemi/materials/combinations', {
        method: 'POST', body,
      });
      setResults(d);
      if ((d.candidates || []).length === 0) {
        setGenError('No candidate met the constraints. Loosen them or pick a different block set.');
      }
    } catch (e) {
      setGenError(e?.status === 403
        ? 'Licence required. Activate a trial or paid seat in the Profile panel.'
        : `Generate failed: ${e?.message || 'unknown'}`);
    } finally {
      setGenerating(false);
    }
  }, [selected, constraints]);

  const draftSynthesis = useCallback(async (cand) => {
    setDraftBusy(true);
    setDraftError(null);
    setDraft(null);
    try {
      const compStr = cand.components
        .map((k, i) => `${Math.round(cand.fractions[i] * 100)}% ${k}`)
        .join(' + ');
      const ask = {
        composite: compStr,
        target_application: 'high-capacitance supercapacitor electrode',
        predicted_properties: cand.properties,
        ask: 'Return JSON with keys "steps" (4–8 concrete experimental steps with reagent quantities and conditions) and "rationale" (2–3 sentences on why this composition).',
      };
      const r = await callBackend('/api/v2/alchemi/chat', {
        method: 'POST',
        body: {
          prompt: JSON.stringify(ask),
          system: 'You are a synthesis chemist. Return ONE JSON object exactly. No prose, no markdown.',
        },
      });
      const text = r?.answer || r?.response || r?.text || '';
      const parsed = extractJSON(text);
      const steps = parsed?.steps && Array.isArray(parsed.steps)
        ? parsed.steps.map(stepToString).filter(Boolean).slice(0, 12)
        : [text.trim() || 'Model returned an empty response.'];
      setDraft({
        steps,
        rationale: stepToString(parsed?.rationale) || '',
      });
    } catch (e) {
      setDraftError(e?.status === 403
        ? 'Licence or AI key needed for synthesis drafting. Set NVIDIA_API_KEY in Profile → Settings.'
        : `Draft failed: ${e?.message || 'unknown'}`);
    } finally {
      setDraftBusy(false);
    }
  }, []);

  return (
    <div className="animate-in" style={{
      display: 'grid',
      gridTemplateColumns: 'minmax(280px, 320px) minmax(320px, 1fr) minmax(360px, 480px)',
      gap: 14, height: '100%', overflow: 'hidden',
    }}>
      {/* ── PANE 1 — Library ──────────────────────────────── */}
      <Pane>
        <Header icon={Package} title="Materials library"
          subtitle={`${library.length} curated blocks · click to add`} />
        <div style={{ display: 'flex', gap: 8, marginBottom: 8 }}>
          <div style={{ flex: 1, position: 'relative' }}>
            <Search size={13} style={{ position: 'absolute', left: 8, top: '50%', transform: 'translateY(-50%)', color: 'var(--text-tertiary)' }} />
            <input
              value={search}
              onChange={e => setSearch(e.target.value)}
              placeholder="Search MnO₂, graphene, …"
              style={{ ...inputStyle, paddingLeft: 28 }}
            />
          </div>
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 10 }}>
          <CategoryChip label="All" active={!categoryFilter} onClick={() => setCategoryFilter(null)} count={library.length} />
          {categories.map(([cat, n]) => (
            <CategoryChip key={cat} label={cat} active={categoryFilter === cat}
              onClick={() => setCategoryFilter(cat)} count={n} color={CATEGORY_COLORS[cat]} />
          ))}
        </div>

        {libError && <ErrorBox message={libError} />}

        <div style={{ flex: 1, overflowY: 'auto', minHeight: 0, paddingRight: 4 }}>
          {filteredLibrary.length === 0 && (
            <div style={{ padding: '24px 8px', color: 'var(--text-tertiary)', fontSize: 12, textAlign: 'center' }}>
              No matches. Clear filters above.
            </div>
          )}
          {filteredLibrary.map(b => (
            <BlockCard key={b.key} block={b}
              selected={selected.includes(b.key)}
              onToggle={() => toggleBlock(b.key)} />
          ))}
        </div>
      </Pane>

      {/* ── PANE 2 — Selected + Constraints ────────────────── */}
      <Pane>
        <Header icon={Atom} title="Composition design"
          subtitle="Selected blocks, design constraints, generate combinations" />

        <div style={{ marginBottom: 14 }}>
          <SectionLabel>Selected blocks ({selected.length})</SectionLabel>
          {selected.length === 0 && (
            <div style={{
              padding: 16, border: '1px dashed var(--border-secondary)',
              borderRadius: 'var(--radius-sm)', textAlign: 'center',
              fontSize: 12, color: 'var(--text-tertiary)',
            }}>
              Click blocks in the library to add them here.
            </div>
          )}
          {selected.length > 0 && (
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
              {selected.map(k => {
                const b = library.find(x => x.key === k);
                return (
                  <button
                    key={k}
                    onClick={() => toggleBlock(k)}
                    title={`Remove ${b?.display_name || k}`}
                    style={{
                      display: 'inline-flex', alignItems: 'center', gap: 6,
                      padding: '5px 9px', fontSize: 11.5, fontWeight: 500,
                      background: 'var(--accent-muted)',
                      color: 'var(--accent)',
                      border: '1px solid var(--accent-border)',
                      borderRadius: 99, cursor: 'pointer',
                    }}
                  >
                    {b?.display_name || k}
                    <X size={12} />
                  </button>
                );
              })}
              <button
                onClick={() => setSelected([])}
                style={{
                  fontSize: 11, padding: '5px 9px',
                  background: 'transparent', color: 'var(--text-tertiary)',
                  border: '1px solid var(--border-primary)', borderRadius: 99, cursor: 'pointer',
                }}
              >
                Clear
              </button>
            </div>
          )}
        </div>

        <div style={{ marginBottom: 14 }}>
          <SectionLabel><Filter size={11} style={{ verticalAlign: -1, marginRight: 4 }} />Constraints</SectionLabel>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
            <NumberField
              label="Min capacitance (F/g)"
              value={constraints.min_capacitance_F_g}
              onChange={v => setConstraints({ ...constraints, min_capacitance_F_g: v })}
              placeholder="e.g. 200" />
            <NumberField
              label="Min conductivity (S/m)"
              value={constraints.min_conductivity_S_m}
              onChange={v => setConstraints({ ...constraints, min_conductivity_S_m: v })}
              placeholder="e.g. 100" />
            <NumberField
              label="Min voltage window (V)"
              value={constraints.min_voltage_window_V}
              onChange={v => setConstraints({ ...constraints, min_voltage_window_V: v })}
              placeholder="e.g. 0.9" />
            <NumberField
              label="Max relative cost (0–1)"
              value={constraints.max_cost_relative}
              onChange={v => setConstraints({ ...constraints, max_cost_relative: v })}
              placeholder="e.g. 0.6" />
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginTop: 10 }}>
            <SelectField
              label="Max components"
              value={constraints.max_components}
              onChange={v => setConstraints({ ...constraints, max_components: Number(v) })}
              options={[1, 2, 3, 4, 5].map(n => [n, `${n}-component`])}
            />
            <SelectField
              label="Mass-fraction step"
              value={constraints.step_pct}
              onChange={v => setConstraints({ ...constraints, step_pct: Number(v) })}
              options={[10, 20, 25, 33, 50].map(p => [p, `${p}%`])}
            />
          </div>

          <label style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 10, fontSize: 12, color: 'var(--text-secondary)', cursor: 'pointer' }}>
            <input
              type="checkbox"
              checked={constraints.require_all_selected}
              onChange={e => setConstraints({ ...constraints, require_all_selected: e.target.checked })}
            />
            Require every selected block to appear in the composite
          </label>
        </div>

        {genError && <ErrorBox message={genError} />}

        <button
          onClick={generate}
          disabled={generating || selected.length === 0}
          style={{
            ...primaryBtn,
            opacity: generating || selected.length === 0 ? 0.6 : 1,
            cursor: generating || selected.length === 0 ? 'default' : 'pointer',
            justifyContent: 'center',
          }}
        >
          {generating
            ? <><Loader2 size={14} className="raman-spin" /> Enumerating…</>
            : <><Sparkles size={14} /> Generate combinations</>}
        </button>

        {results && !genError && (
          <div style={{ marginTop: 10, fontSize: 11.5, color: 'var(--text-tertiary)' }}>
            Evaluated {results.total_evaluated} composite{results.total_evaluated === 1 ? '' : 's'} · showing top {results.candidates.length}
          </div>
        )}
      </Pane>

      {/* ── PANE 3 — Ranked candidates / details ────────────── */}
      <Pane>
        <Header icon={ListFilter} title="Ranked candidates"
          subtitle={picked ? 'Click a candidate to see another' : 'Click a row for full properties'} />

        {!results && !generating && (
          <div style={{ padding: 18, color: 'var(--text-tertiary)', fontSize: 12 }}>
            Pick blocks, set constraints, and press <strong>Generate combinations</strong>. The
            combinator will enumerate every k-component composition (mass-fraction step
            you choose), apply mixture rules, and rank by score.
          </div>
        )}

        {results && (
          <div style={{ flex: 1, overflowY: 'auto', minHeight: 0, paddingRight: 4 }}>
            {results.candidates.map((c, i) => (
              <CandidateRow
                key={i}
                index={i + 1}
                cand={c}
                library={library}
                selected={picked === c}
                onClick={() => setPicked(picked === c ? null : c)}
              />
            ))}
          </div>
        )}

        {picked && (
          <div style={{
            marginTop: 10, paddingTop: 10,
            borderTop: '1px solid var(--border-primary)',
            display: 'flex', flexDirection: 'column', gap: 8,
          }}>
            <SectionLabel>Selected candidate</SectionLabel>
            <PropertyTable cand={picked} library={library} />
            <button
              onClick={() => draftSynthesis(picked)}
              disabled={draftBusy}
              style={{ ...secondaryBtn, justifyContent: 'center' }}
            >
              {draftBusy
                ? <><Loader2 size={13} className="raman-spin" /> Drafting protocol…</>
                : <><Beaker size={13} /> Draft synthesis with NIM</>}
            </button>
            {draftError && <ErrorBox message={draftError} />}
            {draft && (
              <div style={{
                background: 'var(--bg-surface)',
                border: '1px solid var(--border-primary)',
                borderRadius: 'var(--radius-sm)', padding: 10,
              }}>
                {draft.rationale && (
                  <div style={{ fontSize: 11.5, color: 'var(--text-secondary)', marginBottom: 8, lineHeight: 1.5 }}>
                    {draft.rationale}
                  </div>
                )}
                <ol style={{ paddingLeft: 18, margin: 0, fontSize: 12, color: 'var(--text-primary)', lineHeight: 1.5 }}>
                  {draft.steps.map((s, i) => <li key={i} style={{ marginBottom: 4 }}>{s}</li>)}
                </ol>
              </div>
            )}
          </div>
        )}
      </Pane>
    </div>
  );
}

// ── Sub-components ──────────────────────────────────────────────

function Pane({ children }) {
  return (
    <div style={{
      background: 'var(--bg-surface)',
      border: '1px solid var(--border-primary)',
      borderRadius: 'var(--radius-md)',
      padding: 14,
      display: 'flex', flexDirection: 'column',
      minHeight: 0,
      overflow: 'hidden',
      boxShadow: 'var(--shadow-sm)',
    }}>
      {children}
    </div>
  );
}

function Header({ icon: Icon, title, subtitle }) {
  return (
    <div style={{ marginBottom: 12 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        <Icon size={15} strokeWidth={1.75} style={{ color: 'var(--accent)' }} />
        <div style={{ fontSize: 13.5, fontWeight: 600, color: 'var(--text-primary)' }}>{title}</div>
      </div>
      {subtitle && <div style={{ marginTop: 2, fontSize: 11.5, color: 'var(--text-tertiary)' }}>{subtitle}</div>}
    </div>
  );
}

function SectionLabel({ children }) {
  return (
    <div style={{
      fontSize: 11, fontWeight: 500, color: 'var(--text-tertiary)',
      marginBottom: 6, textTransform: 'uppercase', letterSpacing: '0.04em',
    }}>
      {children}
    </div>
  );
}

function CategoryChip({ label, count, active, onClick, color }) {
  return (
    <button
      onClick={onClick}
      style={{
        padding: '3px 8px', fontSize: 10.5, fontWeight: 500,
        borderRadius: 99,
        background: active ? (color || 'var(--accent)') : 'var(--bg-elevated)',
        color: active ? '#fff' : 'var(--text-secondary)',
        border: `1px solid ${active ? (color || 'var(--accent)') : 'var(--border-primary)'}`,
        cursor: 'pointer',
        display: 'inline-flex', alignItems: 'center', gap: 4,
      }}
    >
      {label}
      <span style={{ opacity: 0.7, fontSize: 9.5 }}>{count}</span>
    </button>
  );
}

function BlockCard({ block, selected, onToggle }) {
  const color = CATEGORY_COLORS[block.category] || 'var(--text-tertiary)';
  return (
    <div
      onClick={onToggle}
      style={{
        display: 'flex', alignItems: 'center', gap: 10,
        padding: '8px 10px',
        marginBottom: 4,
        borderRadius: 'var(--radius-sm)',
        background: selected ? 'var(--accent-muted)' : 'transparent',
        border: '1px solid ' + (selected ? 'var(--accent-border)' : 'transparent'),
        cursor: 'pointer',
        transition: 'background 100ms',
      }}
      onMouseEnter={e => { if (!selected) e.currentTarget.style.background = 'var(--bg-hover)'; }}
      onMouseLeave={e => { if (!selected) e.currentTarget.style.background = 'transparent'; }}
    >
      <span style={{
        width: 6, height: 36, borderRadius: 3,
        background: color, flexShrink: 0,
      }} />
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontSize: 12.5, fontWeight: 500, color: 'var(--text-primary)' }}>
          {block.display_name}
        </div>
        <div style={{ fontSize: 10.5, color: 'var(--text-tertiary)', marginTop: 1, display: 'flex', gap: 8 }}>
          <span>{block.formula}</span>
          <span>·</span>
          <span data-number>σ {fmtNum(block.conductivity_S_m)} S/m</span>
          {block.pseudocapacitive && <><span>·</span><span style={{ color: 'var(--color-success)' }}>pseudo</span></>}
        </div>
      </div>
      {selected
        ? <X size={13} style={{ color: 'var(--accent)' }} />
        : <Plus size={13} style={{ color: 'var(--text-tertiary)' }} />}
    </div>
  );
}

function CandidateRow({ index, cand, library, selected, onClick }) {
  const parts = cand.components.map((k, i) => {
    const b = library.find(x => x.key === k);
    return `${Math.round(cand.fractions[i] * 100)}% ${b?.display_name || k}`;
  }).join(' + ');

  const p = cand.properties || {};
  return (
    <div
      onClick={onClick}
      style={{
        padding: '10px 10px',
        marginBottom: 4,
        borderRadius: 'var(--radius-sm)',
        background: selected ? 'var(--accent-muted)' : 'transparent',
        border: '1px solid ' + (selected ? 'var(--accent-border)' : 'var(--border-primary)'),
        cursor: 'pointer',
        transition: 'background 100ms',
      }}
      onMouseEnter={e => { if (!selected) e.currentTarget.style.background = 'var(--bg-hover)'; }}
      onMouseLeave={e => { if (!selected) e.currentTarget.style.background = 'transparent'; }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
        <span data-number style={{
          minWidth: 22, padding: '1px 6px',
          fontSize: 11, fontWeight: 600,
          background: 'var(--bg-elevated)',
          color: 'var(--text-tertiary)',
          borderRadius: 4, textAlign: 'center',
        }}>{index}</span>
        <div style={{ fontSize: 12, fontWeight: 500, color: 'var(--text-primary)', flex: 1 }}>
          {parts}
        </div>
        <span data-number style={{
          fontSize: 11.5, fontWeight: 600,
          color: 'var(--accent)',
          padding: '1px 6px',
          background: 'var(--accent-muted)',
          borderRadius: 4,
        }}>
          {cand.score.toFixed(2)}
        </span>
      </div>
      <div style={{
        display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 6,
        fontSize: 11, color: 'var(--text-tertiary)',
      }}>
        <Mini label="Cs" value={fmtNum(p.capacitance_F_g, 0)} unit="F/g" />
        <Mini label="σ" value={fmtNum(p.conductivity_S_m)} unit="S/m" />
        <Mini label="V" value={fmtNum(p.voltage_window_V)} unit="V" />
        <Mini label="cost" value={fmtNum(p.cost_relative)} unit="" />
      </div>
    </div>
  );
}

function Mini({ label, value, unit }) {
  return (
    <div>
      <span style={{ color: 'var(--text-tertiary)', marginRight: 4 }}>{label}</span>
      <span data-number style={{ color: 'var(--text-primary)' }}>{value}</span>
      {unit && <span style={{ color: 'var(--text-tertiary)', marginLeft: 2 }}>{unit}</span>}
    </div>
  );
}

function PropertyTable({ cand, library }) {
  const p = cand.properties || {};
  const rows = [
    ['Capacitance',           fmtNum(p.capacitance_F_g, 0),         'F/g'],
    ['Conductivity',          fmtNum(p.conductivity_S_m),           'S/m'],
    ['Voltage window',        fmtNum(p.voltage_window_V),           'V'],
    ['Energy density',        fmtNum(p.energy_density_Wh_per_kg),   'Wh/kg'],
    ['Density',               fmtNum(p.density_g_cm3),              'g/cm³'],
    ['Surface area',          fmtNum(p.surface_area_m2_g, 0),       'm²/g'],
    ['Pseudocapacitive %',    fmtNum((p.pseudocapacitive_fraction || 0) * 100, 0), '%'],
    ['Cost (relative)',       fmtNum(p.cost_relative),              ''],
  ];
  return (
    <div style={{
      background: 'var(--bg-elevated)',
      border: '1px solid var(--border-primary)',
      borderRadius: 'var(--radius-sm)',
      padding: 10,
    }}>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 6 }}>
        {rows.map(([k, v, u]) => (
          <div key={k} style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11.5 }}>
            <span style={{ color: 'var(--text-tertiary)' }}>{k}</span>
            <span data-number style={{ color: 'var(--text-primary)', fontWeight: 500 }}>
              {v}{u && <span style={{ color: 'var(--text-tertiary)', marginLeft: 3 }}>{u}</span>}
            </span>
          </div>
        ))}
      </div>
      {cand.reasons?.length > 0 && (
        <ul style={{
          margin: '8px 0 0 14px', padding: 0,
          fontSize: 11, color: 'var(--text-secondary)',
        }}>
          {cand.reasons.map((r, i) => <li key={i} style={{ marginBottom: 2 }}>{r}</li>)}
        </ul>
      )}
    </div>
  );
}

function NumberField({ label, value, onChange, placeholder }) {
  return (
    <label style={{ display: 'block' }}>
      <div style={{ fontSize: 11, color: 'var(--text-secondary)', marginBottom: 3 }}>{label}</div>
      <input
        value={value}
        onChange={e => onChange(e.target.value)}
        placeholder={placeholder}
        inputMode="decimal"
        style={inputStyle}
      />
    </label>
  );
}

function SelectField({ label, value, onChange, options }) {
  return (
    <label style={{ display: 'block' }}>
      <div style={{ fontSize: 11, color: 'var(--text-secondary)', marginBottom: 3 }}>{label}</div>
      <select value={value} onChange={e => onChange(e.target.value)} style={inputStyle}>
        {options.map(([v, l]) => <option key={v} value={v}>{l}</option>)}
      </select>
    </label>
  );
}

function ErrorBox({ message }) {
  return (
    <div style={{
      display: 'flex', alignItems: 'flex-start', gap: 8,
      padding: 8, marginBottom: 10,
      background: 'rgba(220, 38, 38, 0.06)',
      border: '1px solid rgba(220, 38, 38, 0.25)',
      borderRadius: 'var(--radius-sm)',
      fontSize: 11.5, color: 'var(--color-error)',
      lineHeight: 1.4,
    }}>
      <AlertCircle size={13} style={{ flexShrink: 0, marginTop: 1 }} />
      <span>{message}</span>
    </div>
  );
}

const inputStyle = {
  width: '100%',
  background: 'var(--bg-input)',
  border: '1px solid var(--border-primary)',
  borderRadius: 'var(--radius-sm)',
  padding: '6px 9px',
  fontSize: 12,
  fontFamily: 'var(--font-ui)',
  color: 'var(--text-primary)',
  outline: 'none',
  transition: 'border-color 150ms',
};

const primaryBtn = {
  padding: '9px 14px',
  background: 'var(--accent)',
  color: '#fff',
  border: 'none',
  borderRadius: 'var(--radius-sm)',
  fontSize: 12.5,
  fontWeight: 500,
  cursor: 'pointer',
  display: 'inline-flex', alignItems: 'center', gap: 6,
  fontFamily: 'var(--font-ui)',
};

const secondaryBtn = {
  padding: '7px 12px',
  background: 'transparent',
  color: 'var(--text-primary)',
  border: '1px solid var(--border-secondary)',
  borderRadius: 'var(--radius-sm)',
  fontSize: 12,
  cursor: 'pointer',
  display: 'inline-flex', alignItems: 'center', gap: 6,
  fontFamily: 'var(--font-ui)',
};

// ── helpers (kept in this file so the canvas is self-contained) ──

function extractJSON(text) {
  if (!text) return null;
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  const candidate = fenced ? fenced[1] : text;
  const start = candidate.search(/[\[{]/);
  if (start < 0) return null;
  const sliced = candidate.slice(start);
  try { return JSON.parse(sliced); } catch { /* fallthrough */ }
  for (let end = sliced.length; end > 0; end--) {
    try { return JSON.parse(sliced.slice(0, end)); } catch { /* keep shrinking */ }
  }
  return null;
}

function stepToString(s) {
  if (s == null) return '';
  if (typeof s === 'string') return s.trim();
  if (typeof s === 'number' || typeof s === 'boolean') return String(s);
  if (Array.isArray(s)) return s.map(stepToString).filter(Boolean).join(' · ');
  if (typeof s === 'object') {
    const main = s.action || s.description || s.text || s.detail || s.instruction || s.step;
    const aux = [];
    if (s.reagents) aux.push(`reagents: ${stepToString(s.reagents)}`);
    if (s.conditions) aux.push(`conditions: ${stepToString(s.conditions)}`);
    if (s.duration_min) aux.push(`${s.duration_min} min`);
    if (s.temperature_C != null) aux.push(`${s.temperature_C} °C`);
    const tail = aux.length ? ` (${aux.join(', ')})` : '';
    if (typeof main === 'string') return main.trim() + tail;
    return Object.entries(s)
      .filter(([, v]) => v != null && (typeof v !== 'object' || Array.isArray(v)))
      .map(([k, v]) => `${k}: ${stepToString(v)}`)
      .join(' · ');
  }
  return String(s);
}
