import React, { useState, useCallback, useMemo, useEffect } from 'react';
import ReactFlow, {
  Controls,
  Background,
  useNodesState,
  useEdgesState,
  addEdge,
  Handle,
  Position,
} from 'reactflow';
import 'reactflow/dist/style.css';
import {
  BrainCircuit, FlaskConical, Beaker, Database, Target, BarChart3, Play,
  Sparkles, Loader2,
} from 'lucide-react';
import SynthesisAnimator from './SynthesisAnimator';
import { DB } from './MaterialsExplorer';

/**
 * Alchemist Canvas — synthesis planning workspace.
 *
 * Three-stage flow on a React Flow graph:
 *   Constraints + Target → NIM-grounded planner → Protocol + Predicted properties
 *
 * Each node renders calm, sentence-case labels. Real values come from the
 * backend (`/api/v2/alchemi/properties` and `/api/v2/alchemi/chat`); when
 * AI features are inactive (no NVIDIA_API_KEY) the planner returns curated
 * DB values and we surface that as the provenance ("Curated DB" rather
 * than "Generated by Llama-3.3-70B").
 */

const COLORS = {
  constraint: 'var(--color-warning)',  // amber
  target:     'var(--color-success)',  // green
  llm:        'var(--accent)',          // steel blue
  protocol:   'var(--accent)',
  validator:  '#a78bfa',                // soft violet
};

// ── Reusable visual primitives ─────────────────────────────────────────────

function NodeShell({ children, accent, width = 300 }) {
  return (
    <div style={{
      width,
      background: 'var(--bg-surface)',
      border: '1px solid var(--border-primary)',
      borderRadius: 'var(--radius-md)',
      boxShadow: 'var(--shadow-md)',
      overflow: 'hidden',
      position: 'relative',
    }}>
      <span style={{
        position: 'absolute', left: 0, top: 0, bottom: 0, width: 3, background: accent,
        borderTopLeftRadius: 'var(--radius-md)', borderBottomLeftRadius: 'var(--radius-md)',
      }} />
      {children}
    </div>
  );
}

function NodeHeader({ icon: Icon, accent, title, subtitle, badge }) {
  return (
    <div style={{
      display: 'flex', alignItems: 'center', gap: 10,
      padding: '12px 14px',
      borderBottom: '1px solid var(--border-primary)',
    }}>
      <div style={{
        width: 26, height: 26,
        borderRadius: 'var(--radius-sm)',
        background: 'var(--bg-elevated)',
        border: `1px solid ${accent === 'var(--accent)' ? 'var(--accent-border)' : 'var(--border-secondary)'}`,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        flexShrink: 0,
      }}>
        <Icon size={14} strokeWidth={1.75} style={{ color: accent }} />
      </div>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontSize: 12.5, fontWeight: 600, color: 'var(--text-primary)' }}>{title}</div>
        {subtitle && (
          <div style={{ fontSize: 11, color: 'var(--text-tertiary)', marginTop: 1 }}>
            {subtitle}
          </div>
        )}
      </div>
      {badge && (
        <span style={{
          fontSize: 10, fontWeight: 500,
          padding: '2px 7px', borderRadius: 99,
          background: 'var(--bg-elevated)', color: 'var(--text-secondary)',
          border: '1px solid var(--border-primary)',
        }}>
          {badge}
        </span>
      )}
    </div>
  );
}

const Dot = ({ accent }) => (
  <Handle type="source" position={Position.Right} style={{
    width: 8, height: 8, background: accent, border: '2px solid var(--bg-primary)',
  }} />
);
const Slot = ({ accent }) => (
  <Handle type="target" position={Position.Left} style={{
    width: 8, height: 8, background: accent, border: '2px solid var(--bg-primary)',
  }} />
);

// ── Node types ─────────────────────────────────────────────────────────────

function ConstraintNode({ data }) {
  return (
    <NodeShell accent={COLORS.constraint} width={280}>
      <NodeHeader icon={Database} accent={COLORS.constraint}
        title="Constraints" subtitle="Budget and available reagents" />
      <div style={{ padding: '12px 14px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 10 }}>
          <span style={{ fontSize: 11, color: 'var(--text-tertiary)' }}>Budget</span>
          <span data-number style={{ fontSize: 13, fontWeight: 500, color: 'var(--text-primary)' }}>
            ₹{data.budget}
          </span>
        </div>
        <div style={{ fontSize: 11, color: 'var(--text-tertiary)', marginBottom: 6 }}>Inventory</div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
          {data.inventory.map(item => (
            <span key={item} style={{
              fontSize: 10.5, padding: '3px 8px', borderRadius: 99,
              background: 'var(--bg-elevated)', color: 'var(--text-secondary)',
              border: '1px solid var(--border-primary)',
            }}>
              {item}
            </span>
          ))}
        </div>
      </div>
      <Dot accent={COLORS.constraint} />
    </NodeShell>
  );
}

function TargetNode({ data }) {
  return (
    <NodeShell accent={COLORS.target} width={280}>
      <NodeHeader icon={Target} accent={COLORS.target}
        title="Target" subtitle="What you want to make" />
      <div style={{ padding: '12px 14px', fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.5 }}>
        {data.objective}
      </div>
      <Dot accent={COLORS.target} />
    </NodeShell>
  );
}

function LLMNode({ data }) {
  const generating = data.status === 'generating';
  return (
    <NodeShell accent={COLORS.llm} width={300}>
      <Slot accent={COLORS.llm} />
      <NodeHeader icon={BrainCircuit} accent={COLORS.llm}
        title="Synthesis planner"
        subtitle={data.modelLabel || 'NVIDIA NIM (Llama-3.3-70B)'}
        badge={generating ? 'Working' : 'Idle'}
      />
      <div style={{
        padding: '12px 14px', fontSize: 11.5, color: 'var(--text-secondary)',
        display: 'flex', alignItems: 'center', gap: 8,
      }}>
        {generating
          ? <Loader2 size={13} style={{ color: 'var(--accent)' }} className="raman-spin" />
          : <Sparkles size={13} style={{ color: 'var(--text-tertiary)' }} />}
        <span>{generating ? 'Generating protocol & properties…' : 'Press Plan synthesis to begin'}</span>
      </div>
      <Dot accent={COLORS.llm} />
    </NodeShell>
  );
}

function ProtocolNode({ data }) {
  const [isPlaying, setIsPlaying] = useState(false);
  const formattedSteps = data.steps.map(s => ({
    action: s, phase: 'Synthesis', duration_min: 5,
    critical: /exotherm|pyroph|caution|critical/i.test(s),
  }));

  return (
    <NodeShell accent={COLORS.protocol} width={420}>
      <Slot accent={COLORS.protocol} />
      <NodeHeader icon={FlaskConical} accent={COLORS.protocol}
        title="Synthesis protocol"
        subtitle={data.material} />
      <div style={{ padding: '12px 14px' }}>
        {!isPlaying ? (
          <>
            <ol style={{ paddingLeft: 0, listStyle: 'none', margin: 0, display: 'flex', flexDirection: 'column', gap: 6 }}>
              {data.steps.map((s, i) => (
                <li key={i} style={{
                  display: 'flex', gap: 10,
                  padding: '8px 10px',
                  background: 'var(--bg-elevated)',
                  border: '1px solid var(--border-primary)',
                  borderRadius: 'var(--radius-sm)',
                  fontSize: 12, color: 'var(--text-primary)', lineHeight: 1.45,
                }}>
                  <span data-number style={{
                    color: 'var(--accent)', fontWeight: 500, minWidth: 18,
                  }}>
                    {(i + 1).toString().padStart(2, '0')}
                  </span>
                  <span>{s}</span>
                </li>
              ))}
            </ol>
            <button
              onClick={() => setIsPlaying(true)}
              style={primaryBtn}
              onMouseEnter={e => e.currentTarget.style.background = 'var(--accent-hover)'}
              onMouseLeave={e => e.currentTarget.style.background = 'var(--accent)'}
            >
              <Play size={13} fill="currentColor" /> Animate synthesis
            </button>
          </>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            <SynthesisAnimator protocolSteps={formattedSteps} materialAtoms={data.atoms} />
            <button onClick={() => setIsPlaying(false)} style={secondaryBtn}>Stop animation</button>
          </div>
        )}
      </div>
      <Dot accent={COLORS.protocol} />
    </NodeShell>
  );
}

function SimulationNode({ data }) {
  const rows = [
    { label: 'Band gap',           value: data.bandgap,     unit: 'eV' },
    { label: 'Specific capacitance', value: data.capacitance, unit: 'F/g' },
  ];
  const provenanceLabel = {
    curated:        'Curated DB',
    lab_dataset:    'User lab dataset',
    llm_estimate:   'LLM estimate',
    llm:            'LLM estimate',
  }[data.provenance] || data.provenance || 'Unknown';

  return (
    <NodeShell accent={COLORS.validator} width={300}>
      <Slot accent={COLORS.validator} />
      <NodeHeader icon={BarChart3} accent={COLORS.validator}
        title="Predicted properties"
        subtitle={`Source: ${provenanceLabel}`}
      />
      <div style={{ padding: '12px 14px', display: 'flex', flexDirection: 'column', gap: 8 }}>
        {rows.map(r => (
          <div key={r.label} style={{
            display: 'flex', justifyContent: 'space-between', alignItems: 'baseline',
            padding: '8px 12px',
            background: 'var(--bg-elevated)',
            border: '1px solid var(--border-primary)',
            borderRadius: 'var(--radius-sm)',
          }}>
            <span style={{ fontSize: 11.5, color: 'var(--text-secondary)' }}>{r.label}</span>
            <span data-number style={{ fontSize: 13, fontWeight: 500, color: 'var(--text-primary)' }}>
              {r.value}
              {r.value !== 'n/a' && <span style={{ marginLeft: 4, fontSize: 10.5, color: 'var(--text-tertiary)' }}>{r.unit}</span>}
            </span>
          </div>
        ))}
      </div>
    </NodeShell>
  );
}

// ── Initial graph ──────────────────────────────────────────────────────────

const initialNodes = [
  { id: 'inventory', type: 'constraint', position: { x: 30, y: 90 },
    data: { budget: 500, location: 'Bangalore, IN', inventory: ['Graphite Powder', 'H2SO4', 'KMnO4', 'Microwave'] } },
  { id: 'target', type: 'target', position: { x: 30, y: 360 },
    data: { objective: 'High-capacitance supercapacitor electrode for wearables.' } },
  { id: 'llm', type: 'llm', position: { x: 460, y: 220 }, data: { status: 'idle' } },
];

const initialEdges = [
  { id: 'e1', source: 'inventory', target: 'llm', animated: true,
    style: { stroke: COLORS.constraint, strokeWidth: 1.5, opacity: 0.6 } },
  { id: 'e2', source: 'target', target: 'llm', animated: true,
    style: { stroke: COLORS.target, strokeWidth: 1.5, opacity: 0.6 } },
];

// ── Backend helpers ────────────────────────────────────────────────────────

const BACKEND_URL = (typeof window !== 'undefined' && window.raman) ? null : 'http://127.0.0.1:8000';

async function callBackend(path, opts = {}) {
  // The Electron preload bridge (window.raman.api) exposes `call(path, body)`
  // for POST and `get(path)` for GET. There's no `post()` — using one was
  // the source of "d.post is not a function" in earlier builds.
  const api = (typeof window !== 'undefined' && window.raman) ? window.raman.api : null;
  if (api) {
    return opts.method === 'POST' ? api.call(path, opts.body) : api.get(path);
  }
  const res = await fetch(`${BACKEND_URL}${path}`, {
    method: opts.method || 'GET',
    headers: { 'Content-Type': 'application/json' },
    body: opts.body ? JSON.stringify(opts.body) : undefined,
  });
  if (!res.ok) {
    const text = await res.text();
    const err = new Error(`HTTP ${res.status}: ${text.slice(0, 200)}`);
    err.status = res.status;
    throw err;
  }
  return res.json();
}

function extractJSON(text) {
  if (!text) return null;
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  const candidate = fenced ? fenced[1] : text;
  const start = candidate.search(/[\[{]/);
  if (start < 0) return null;
  const sliced = candidate.slice(start);
  try { return JSON.parse(sliced); } catch { /* fallthrough */ }
  for (let end = sliced.length; end > 0; end--) {
    try { return JSON.parse(sliced.slice(0, end)); } catch { /* keep shrinking */ }
  }
  return null;
}

// ── Main ───────────────────────────────────────────────────────────────────

export default function AlchemistCanvas() {
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);
  const [isGenerating, setIsGenerating] = useState(false);
  const [targetFormula, setTargetFormula] = useState('MnO2');
  const [error, setError] = useState(null);
  const [activity, setActivity] = useState([]);   // {ts, kind, text}
  const [aiConfigured, setAiConfigured] = useState(null);

  // Pull AI status once on mount so the planner node can show the right label.
  useEffect(() => {
    (async () => {
      try {
        const s = await callBackend('/api/v2/alchemi/status');
        setAiConfigured(!!s?.configured);
        setNodes(nds => nds.map(n => n.id === 'llm'
          ? { ...n, data: { ...n.data, modelLabel: s?.configured ? `NVIDIA NIM (${s?.default_model || 'Llama-3.3-70B'})` : 'Local fallback (no API key)' } }
          : n));
      } catch {
        setAiConfigured(false);
      }
    })();
  }, [setNodes]);

  const nodeTypes = useMemo(() => ({
    constraint: ConstraintNode,
    target: TargetNode,
    llm: LLMNode,
    protocol: ProtocolNode,
    simulation: SimulationNode,
  }), []);

  const onConnect = useCallback((params) => setEdges(eds => addEdge(params, eds)), [setEdges]);

  const log = (kind, text) => setActivity(prev => [
    ...prev.slice(-15),
    { ts: new Date(), kind, text },
  ]);

  const runSynthesis = async () => {
    setIsGenerating(true);
    setError(null);
    setNodes(nds => nds.map(n => n.id === 'llm' ? { ...n, data: { ...n.data, status: 'generating' } } : n));

    const formula = (targetFormula || '').trim();
    if (!formula) {
      setError('Enter a target formula first (e.g. MnO2).');
      setIsGenerating(false);
      setNodes(nds => nds.map(n => n.id === 'llm' ? { ...n, data: { ...n.data, status: 'idle' } } : n));
      return;
    }

    try {
      log('info', `Looking up properties for ${formula}…`);
      const props = await callBackend('/api/v2/alchemi/properties', {
        method: 'POST',
        body: { formula },
      });

      log('info', 'Asking the planner for a synthesis protocol…');
      const target = nodes.find(n => n.id === 'target')?.data?.objective || '';
      const inventory = nodes.find(n => n.id === 'inventory')?.data?.inventory || [];
      const promptObj = {
        target_formula: formula,
        target_application: target,
        available_inventory: inventory,
        ask: 'Return JSON with keys "steps" (4–8 concrete experimental steps with reagent quantities and conditions) and "rationale" (2–3 sentences).',
      };
      const chatResp = await callBackend('/api/v2/alchemi/chat', {
        method: 'POST',
        body: {
          prompt: JSON.stringify(promptObj),
          system: 'You are a synthesis chemist. Reply with one valid JSON object matching the requested shape. No prose, no markdown fences.',
        },
      });

      const responseText = chatResp.answer || chatResp.response || chatResp.text || '';
      const parsed = extractJSON(responseText);
      const steps = parsed?.steps && Array.isArray(parsed.steps)
        ? parsed.steps.slice(0, 12)
        : [responseText.trim() || 'The planner returned an empty response.'];
      const rationale = parsed?.rationale || '';

      const dbHit = DB.find(m =>
        m.name?.toLowerCase().includes(formula.toLowerCase()) ||
        formula.toLowerCase().includes(m.name?.toLowerCase().split(' ')[0]?.toLowerCase()),
      );

      const protocolNode = {
        id: 'protocol',
        type: 'protocol',
        position: { x: 880, y: 50 },
        data: { material: formula, atoms: dbHit?.atoms || [], steps },
      };

      const bandgap = props?.band_gap_ev ?? props?.band_gap ?? props?.properties?.band_gap_ev;
      const capacitance = props?.specific_capacitance_f_g ?? props?.properties?.specific_capacitance_f_g;
      const provenance = props?.source || 'curated';

      const simNode = {
        id: 'sim',
        type: 'simulation',
        position: { x: 880, y: 470 },
        data: {
          bandgap: bandgap != null ? Number(bandgap).toFixed(3) : 'n/a',
          capacitance: capacitance != null ? Number(capacitance).toFixed(2) : 'n/a',
          provenance,
        },
      };

      setNodes(nds => [
        ...nds
          .filter(n => n.id !== 'protocol' && n.id !== 'sim')
          .map(n => n.id === 'llm' ? { ...n, data: { ...n.data, status: 'idle' } } : n),
        protocolNode,
        simNode,
      ]);
      setEdges(eds => [
        ...eds.filter(e => e.id !== 'e3' && e.id !== 'e4'),
        { id: 'e3', source: 'llm', target: 'protocol', animated: true, style: { stroke: COLORS.llm, strokeWidth: 1.5 } },
        { id: 'e4', source: 'llm', target: 'sim', animated: true, style: { stroke: COLORS.llm, strokeWidth: 1.5 } },
      ]);

      if (rationale) log('rationale', rationale);
      log('source', `Properties source: ${provenance}`);
      log('done', 'Plan ready.');
    } catch (err) {
      const msg = err?.status === 403
        ? 'Licence required — activate a trial or paid seat to use Alchemist Canvas.'
        : err?.status === 503 || err?.message?.includes('Cannot reach')
        ? 'Backend unreachable. Make sure the local RĀMAN service is running.'
        : `Synthesis failed: ${err?.message || 'unknown error'}`;
      setError(msg);
      log('error', msg);
      setNodes(nds => nds.map(n => n.id === 'llm' ? { ...n, data: { ...n.data, status: 'idle' } } : n));
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="animate-in" style={{
      height: '100%', display: 'flex', flexDirection: 'column',
      background: 'var(--bg-primary)',
    }}>
      {/* Header */}
      <div style={{
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        padding: '14px 20px',
        borderBottom: '1px solid var(--border-primary)',
        background: 'var(--bg-secondary)',
        flexShrink: 0,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <div style={{
            width: 30, height: 30,
            borderRadius: 'var(--radius-sm)',
            background: 'var(--bg-elevated)',
            border: '1px solid var(--border-secondary)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <Beaker size={16} color="var(--accent)" strokeWidth={1.75} />
          </div>
          <div>
            <h2 style={{ margin: 0, fontSize: 14, fontWeight: 600, color: 'var(--text-primary)' }}>
              Alchemist Canvas
            </h2>
            <div style={{ fontSize: 11.5, color: 'var(--text-tertiary)', marginTop: 1 }}>
              Plan a synthesis route from constraints + target.
              {aiConfigured === false && (
                <span style={{ color: 'var(--color-warning)', marginLeft: 6 }}>
                  · NVIDIA_API_KEY not set — using curated DB only
                </span>
              )}
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
          <input
            type="text"
            value={targetFormula}
            onChange={e => setTargetFormula(e.target.value)}
            placeholder="Target formula (e.g. MnO2)"
            disabled={isGenerating}
            spellCheck={false}
            onKeyDown={e => { if (e.key === 'Enter' && !isGenerating) runSynthesis(); }}
            style={{
              fontFamily: 'var(--font-data)',
              fontSize: 12,
              background: 'var(--bg-input)',
              color: 'var(--text-primary)',
              border: '1px solid var(--border-primary)',
              borderRadius: 'var(--radius-sm)',
              padding: '7px 10px',
              width: 200, outline: 'none',
              transition: 'border-color var(--transition)',
            }}
            onFocus={e => e.currentTarget.style.borderColor = 'var(--accent-border)'}
            onBlur={e => e.currentTarget.style.borderColor = 'var(--border-primary)'}
          />
          <button onClick={runSynthesis} disabled={isGenerating} style={{
            ...primaryBtn,
            opacity: isGenerating ? 0.7 : 1,
            cursor: isGenerating ? 'wait' : 'pointer',
          }}>
            {isGenerating
              ? <><Loader2 size={13} className="raman-spin" /> Working…</>
              : <><Sparkles size={13} /> Plan synthesis</>}
          </button>
        </div>
      </div>

      {error && (
        <div role="alert" style={{
          padding: '10px 20px',
          background: 'rgba(255, 69, 58, 0.08)',
          borderBottom: '1px solid rgba(255, 69, 58, 0.25)',
          color: 'var(--text-primary)', fontSize: 12,
          display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        }}>
          <span><strong style={{ color: 'var(--color-error)' }}>Error:</strong> {error}</span>
          <button onClick={() => setError(null)} style={{
            background: 'transparent', border: '1px solid rgba(255, 69, 58, 0.3)',
            color: 'var(--color-error)', borderRadius: 'var(--radius-sm)',
            padding: '3px 9px', cursor: 'pointer', fontSize: 11,
          }}>Dismiss</button>
        </div>
      )}

      <div style={{ flex: 1, position: 'relative', overflow: 'hidden' }}>
        <ReactFlow
          nodes={nodes}
          edges={edges}
          onNodesChange={onNodesChange}
          onEdgesChange={onEdgesChange}
          onConnect={onConnect}
          nodeTypes={nodeTypes}
          fitView
        >
          <Background gap={20} size={1} color="rgba(255, 255, 255, 0.04)" />
          <Controls style={{
            background: 'var(--bg-elevated)',
            border: '1px solid var(--border-primary)',
            borderRadius: 'var(--radius-sm)',
          }} />
        </ReactFlow>

        {/* Activity log — calm, sentence-case, no terminal vibes */}
        <div style={{
          position: 'absolute', bottom: 18, right: 18,
          width: 360, maxHeight: 220,
          background: 'var(--bg-secondary)',
          border: '1px solid var(--border-primary)',
          borderRadius: 'var(--radius-md)',
          boxShadow: 'var(--shadow-lg)',
          overflow: 'hidden',
          display: 'flex', flexDirection: 'column',
        }}>
          <div style={{
            padding: '8px 12px',
            borderBottom: '1px solid var(--border-primary)',
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            fontSize: 11, color: 'var(--text-secondary)',
          }}>
            <span style={{ fontWeight: 500 }}>Activity</span>
            <span style={{
              width: 6, height: 6, borderRadius: '50%',
              background: isGenerating ? 'var(--color-warning)' : 'var(--color-success)',
              animation: isGenerating ? 'raman-pulse 1.4s ease-in-out infinite' : 'none',
            }} />
          </div>
          <div style={{
            padding: '8px 12px', overflowY: 'auto',
            display: 'flex', flexDirection: 'column', gap: 6,
            fontSize: 11.5, color: 'var(--text-secondary)', lineHeight: 1.4,
          }}>
            {activity.length === 0 && (
              <div style={{ color: 'var(--text-tertiary)' }}>
                Press <strong>Plan synthesis</strong> to start.
              </div>
            )}
            {activity.map((a, i) => (
              <div key={i} style={{
                color: a.kind === 'error' ? 'var(--color-error)'
                     : a.kind === 'done' ? 'var(--color-success)'
                     : a.kind === 'rationale' ? 'var(--text-primary)'
                     : 'var(--text-secondary)',
                opacity: i === activity.length - 1 ? 1 : 0.75,
              }}>
                <span data-number style={{
                  color: 'var(--text-tertiary)', marginRight: 8, fontSize: 10.5,
                }}>
                  {a.ts.toLocaleTimeString('en-GB', { hour12: false })}
                </span>
                {a.text}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

// ── Local button styles ────────────────────────────────────────────────────

const primaryBtn = {
  padding: '8px 14px',
  background: 'var(--accent)',
  color: '#fff',
  border: 'none',
  borderRadius: 'var(--radius-sm)',
  fontSize: 12.5,
  fontWeight: 500,
  cursor: 'pointer',
  display: 'inline-flex',
  alignItems: 'center',
  gap: 6,
  fontFamily: 'var(--font-ui)',
  transition: 'background var(--transition)',
  marginTop: 12,
};

const secondaryBtn = {
  padding: '7px 12px',
  background: 'transparent',
  color: 'var(--text-secondary)',
  border: '1px solid var(--border-secondary)',
  borderRadius: 'var(--radius-sm)',
  fontSize: 12,
  cursor: 'pointer',
  fontFamily: 'var(--font-ui)',
};
